version: 2.1

orbs:
  cfa: continuousauth/npm@2.1.1
  node: electronjs/node@2.3.1

workflows:
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - node/test:
          pre-steps:
            - when:
                condition:
                  - equal: [ '14.16', << matrix.node-version >> ]
                steps:
                  - node/install-rosetta
          executor: node/macos
          name: test-mac-<< matrix.node-version >>
          matrix:
            alias: test-mac
            parameters:
              node-version:
                - '20.9'
                - '18.17'
                - '16.20'
                # Stay below 14.17.0 or nvm tries to download arm64 artifacts which don't exist
                - '14.16'
      - cfa/release:
          requires:
            - test-mac
          filters:
            branches:
              only:
                - main
          context: cfa-release
