step-restore-cache: &step-restore-cache
  restore_cache:
    keys:
      - v2-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
      - v2-dependencies-{{ arch }}

steps-test: &steps-test
  steps:
    - checkout
    - *step-restore-cache
    - run: yarn
    - save_cache:
        paths:
          - node_modules
          - cache
        key: v2-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
    - run: yarn test


version: 2
jobs:
  test-mac:
    macos:
      xcode: "12.4.0"
    <<: *steps-test

  release:
    macos:
      xcode: "12.4.0"
    steps:
      - checkout
      - *step-restore-cache
      - run: yarn
      - run: npx semantic-release@17.4.5
workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test-mac
      - release:
          requires:
            - test-mac
          filters:
            branches:
              only:
                - main

