step-restore-cache: &step-restore-cache
  restore_cache:
    keys:
      - v2-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
      - v2-dependencies-{{ arch }}

steps-test: &steps-test
  steps:
    - checkout
    - *step-restore-cache
    - run: yarn
    - save_cache:
        paths:
          - node_modules
          - cache
        key: v2-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
    - run: yarn test

version: 2.1
orbs:
  cfa: continuousauth/npm@1.0.2
jobs:
  test-mac:
    macos:
      xcode: "13.4.0"
    resource_class: macos.x86.medium.gen2
    <<: *steps-test

workflows:
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test-mac
      - cfa/release:
          requires:
            - test-mac
          filters:
            branches:
              only:
                - main
          context: cfa-release
